### ISSUE TITLE
System running in recovery (initramfs) mode. No changes to settings will be stored and are lost after rebooting. This mode should only be used to install a firmware upgrade

### ISSUE THREAD

**Issue by indexofs** [openwrt/openwrt#10010]
![1](https://user-images.githubusercontent.com/63066788/172617416-e17cebda-9702-4276-8bb6-76e522df3d61.png)

**Comment by indexofs** [comment]
run sysupgrade -n /tmp/openwrt-ramips-mt7621-xiaomi_redmi-router-ac2100-squashfs-sysupgrade.bin
Same mistake

**Comment by Hi-Angel** [comment]
> Same mistake

Unless I am missing something, OpenWRT officially says to use minimal kernel for installation. I think the problem is that they don't mention that minimal kernel should then be upgraded via sysupgrade; and neither does the warning that appears on the web-interface.

<img width="1058" height="305" alt="Image" src="https://github.com/user-attachments/assets/04c09fd2-1fd1-4917-b957-ea88d9a0d07b" />
