### ISSUE TITLE
dnsmasq: require update to support nftset

### ISSUE THREAD

**Issue by lvqier** [openwrt/openwrt#10759]
Sicnce 22.03.0, iptables was replaced by nftables and ipset in firewall was migrated to nftset. But current version of dnsmasq does not support nftset. There's no approach to make things work like filtering traffic with IP sets by DNS.

First version of dnsmasq with nftset support is 2.87, which is still in release candidate.

**Comment by ChemistScript** [comment]
iptables-nft is not working?

**Comment by dave14305** [comment]
> iptables-nft is not working?

dnsmasq cannot populate nftables sets until 2.87 is released with this commit:
https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commitdiff;h=47aefca5e405b4b6627ef952fdc42e61b1baa770;hp=981fb037102306a4ca683f14c8469db4d5e27233

**Comment by ChemistScript** [comment]
I thought iptables-nft able to populate nft sets.

**Comment by harvey-git** [comment]
In order to solve the same problem, I wrote a script and put it in crontab to run, the following is the content of the script

`#!/bin/sh 
i=1;
numset=$((`ipset list|wc -l`-8));
while [ $i -le $numset ] ;
 do ipset list|tail -$i|head -1|sed 's|^|{|'|sed 's|$|}|'|xargs nft add element apric gfwzone  ;
i=$((i+1)) ; 
done
`

**Comment by KeyofBlueS** [comment]
dnsmasq 2.87 has been released https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=tag;h=refs/tags/v2.87 :+1:

**Comment by xabolcs** [comment]
Related PR: #10820

**Comment by 981213** [comment]
dnsmasq is already bumped to 2.87. Closing.
