### ISSUE TITLE
Sending multiple Ctrl+C to UART ttylogin will trigger a system restart

### ISSUE THREAD

**Issue by angliu-muxi** [openwrt/openwrt#11306]
## first enable ttylogin
uci set system.@system[0].ttylogin='1'; uci commit; sync; reboot
## second input root and send multiple Ctrl+C by UART, the system will reboot
```shell
OpenWrt login: ^C^CPlease press Enter to activate this console.
^CPlease press Enter to activate this console.
^CPlease press Enter to activate this console.
^CPlease press Enter to activate this console.
^C[  229.476790] reboot: Restarting system

```
## It seems that during the time /usr/libexec/login.sh exited, procd received the Ctrl+C signal, causing procd to restart the system
ttyS0::askfirst:/usr/libexec/login.sh

**Comment by M95D** [comment]
Why is this a problem?
Even if your router asks for a password on the serial console, anyone with physical access can simply cut the power to reset the router.

**Comment by angliu-muxi** [comment]
> Why is this a problem? Even if your router asks for a password on the serial console, anyone with physical access can simply cut the power to reset the router.

The premise of system restart is that the system administrator knows what is being done, rather than the restart caused by unknown operations. According to the thinking of non-developers, who knows that Ctrl+C will cause system downtime. If the current system is performing core business, the consequences will be is catastrophic

**Comment by mpratt14** [comment]
non-developer would not be using UART

It would be nice if you or someone else could fix this, but I think we can all agree that it is not a critical problem

it seems like your description of the cause is pretty accurate, although fixing it might involve a kernel patch instead of changes to procd, since procd is not in control of what happens when it recieves SIGINT. alternatively, something about blocking or redirecting console to null might be possible, but IIRC, procd actually uses the console to interact with ubusd or something like that...

**Comment by nihilus** [comment]
> non-developer would not be using UART
> 
> It would be nice if you or someone else could fix this, but I think we can all agree that it is not a critical problem
> 
> it seems like your description of the cause is pretty accurate, although fixing it might involve a kernel patch instead of changes to procd, since procd is not in control of what happens when it recieves SIGINT. alternatively, something about blocking or redirecting console to null might be possible, but IIRC, procd actually uses the console to interact with ubusd or something like that...

Well, the thing is that FAE's and support technicians might use console access.
When you have let's say 3 million deployed devices you don't want developers to do field maintenance..

The problem here is that procd gets a controlling TTY during a window period of ~0.5s, which is 100% unintended and a bug.
I'll post a fix to issue later this week.
