### ISSUE TITLE
RPCError

### ISSUE THREAD

**Issue by sherlock9712** [openwrt/openwrt#11571]
Hi, I install OpenWRT on my Raspberry 3 B+. When I access the web to the Interfaces window, it returns this error
```
An error occurred while saving the form:
RPC call to uci/add failed with ubus code 9: Unspecified error
  at ClassConstructor.handleCallReply (https://192.168.1.1/luci-static/resources/rpc.js?v=git-22.288.45147-96ec0cd:15:3)
```
I have seen various posts and some recommend deleting the file found in `/etc/config/system` but it doesn't work for me. it keeps giving me the same problem. What can i do? Thanks

**Comment by jow-** [comment]
The error most likely stems from libuci, could be either IO issues (broken flash, permissions), syntax errors in the configs getting requested or semantic problems (duplicate section ids, duplicate options).

Since you didn't gave any information about the OpenWrt version running as well as the steps leading to the error, no further diagnosis is possible. I suggest to use the OpenWrt forum for support in case the issue persists.
