### ISSUE TITLE
Redirect after System > Backup/Flash Firmware > Upload archive... > Upload

### ISSUE THREAD

**Issue by efairefair** [openwrt/openwrt#11878]
### Describe the bug

When restoring settings from a previously generated archive, the UI redirects to 192.168.1.1, regardless of the IP address of the device being restored.

### OpenWrt version

r20028-43d71ad93e

### OpenWrt target/subtarget

ath79/generic

### Device

Ubiquiti UniFi AC Lite

### Image kind

Official downloaded image

### Steps to reproduce

Configure Netgear R7500v2 openwrt device A to use 192.168.1.1
Configure Ubiquiti Unifi AP Lite openwrt device B to use 192.168.1.253

1) Save B's current configuration System > Backup/Flash Firmware > Generate archive
2) Reload B's configuration: System > Backup/Flash Firmware > Upload archive... > Upload

Notice redirection to A afterwards.

### Expected behaviour

Do not redirect to A.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment]
LuCI has no knowledge of the backup contents, they're handed to the lowlevel sysupgrade utility for restoration. Even if we'd read the backup there would be no reliable way to identify which IP address to redirect to (or the restored configuration might not contain specific IP settings at all, e.g. for DHCP client interfaces).

Due to that, the issue will not be fixed.
