### ISSUE TITLE
Latest snapshot causes boot-looping

### ISSUE THREAD

**Issue by Request-timed-out** [openwrt/openwrt#14119]
### Describe the bug

I always use [OpenWrt Firmware Selector](https://firmware-selector.openwrt.org/?version=SNAPSHOT&target=ath79%2Fgeneric&id=tplink_tl-wdr6500-v2) to build custom images for TP-Link TL-WDR6500, but last day it started boot-looping after update. I also tried the latest official factory snapshot (r24564-78d259e7d2, 2023-12-03 02:23:01), flashed it with breed and it boot-loops too.

I found [this](https://github.com/x-wrt/build-release/releases/tag/v23.10_b202311271303) custom build from 2023-11-27 works, but any latest (both custom and official snapshot) since 2023-12-01 does not.

### OpenWrt version

r24564-78d259e7d2

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

ath79/generic

### Device

TP-Link TL-WDR6500 v2

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by schuettecarsten** [comment]
I can confirm boot-loop/soft-brick on mt7622 (Linksys E8450-ubi), and bcm2711 (Raspiberry Pi 4) too

**Comment by stklcode** [comment]
Same on Ubiquiti airCube AC (ath79/generic).

I suspect some issue with the recent DT changes (nvmem conversion has been done for my device before without issues, maybe not cleaned up properly now).

On my device, failsafe mode works fine, regular boot crashes in a pretty late stage, LEDs show “up“ for a few seconds before reboot. Wired network is available for a short time, but before anything really works, a reboot is triggered.

Didn’t  investigate on this yet, maybe later this week.

**Comment by ascendbeing** [comment]
> Same on Ubiquiti airCube AC (ath79/generic).
> 
> I suspect some issue with the recent DT changes (nvmem conversion has been done for my device before without issues, maybe not cleaned up properly now).
> 
> On my device, failsafe mode works fine, regular boot crashes in a pretty late stage, LEDs show “up“ for a few seconds before reboot. Wired network is available for a short time, but before anything really works, a reboot is triggered.
> 
> Builds on the very same commit with similar changes on other targets (mvebu/cortexa9 and x86) work fine.
> 
> Didn’t investigate on this yet, maybe later this week.

yes that's the same behavior exhibited on Archer c7 v2. LEDs appear to settle to normal but then it goes all LEDs on rinse and repeat

**Comment by ynezz** [comment]
> I can confirm boot-loop/soft-brick on mt7622 (Linksys E8450-ubi)

Interesting, is this some custom build? If so, can you share output of `./scripts/diffconfig.sh` ?

I'm wondering, as there is E8450 in the daily runtime testing testbed, but the issue is not visible there, it works just fine, 78d259e7d2 [passed testing](https://gitlab.com/ynezz/openwrt-device-runtime-testing/-/jobs/5671287472) this morning. The issue is only visible on [ZyXEL GS1900-8/rtl838x](https://lists.openwrt.org/pipermail/openwrt-devel/2023-December/041889.html).

**Comment by nbd168** [comment]
Took me a while to figure out this nasty issue. Seems that mmap has some undocumented extra requirements on some MIPS devices. On affected devices, it needs bigger than PAGE_SIZE alignment in order to avoid issues with CPU data cache aliases. I also improved the code to more gracefully deal with udebug buffer allocation failures. Fix pushed in e03f5e4af735bbd73ac6d3252ce474d4666fd3d5

**Comment by schuettecarsten** [comment]
Works now on my devices. Thank you @nbd168

**Comment by stklcode** [comment]
Same here. Seems to be fixed.

**Comment by oldium** [comment]
Works for me too.

**Comment by oldium** [comment]
If you are unable to build, then I would say your issue is unrelated to boot loop issue. Why to reopen boot loop if boot loop is fixed? Or am I missing something?

**Comment by catsimple** [comment]
> @catsimple - your issue is reported here [openwrt/udebug#1 (comment)](https://github.com/openwrt/udebug/issues/1#issuecomment-1839787598)

thank you :)

**Comment by oldium** [comment]
You have some dependency issue, package built against older/newer versions.
