### ISSUE TITLE
[BMIPS] "gpio-leds" does not work on BCM63168

### ISSUE THREAD

**Issue by rikka0w0** [openwrt/openwrt#14664]
### Describe the bug

I'm trying to add support for F@st3864 in the BMIPS target and found that "gpio-leds" didnt work on the BCM63168 SOC. Here is the relevant [dts](https://github.com/rikka0w0/openwrt-fast3864op/blob/fast3864_master_20240213/target/linux/bmips/dts/bcm63168-sagem-fast-3864-op.dts): 
```
/ {
   < omitted >

	leds {
		compatible = "gpio-leds";

		led@36 {
			gpios = <&gpio 36 GPIO_ACTIVE_LOW>;
			label = "green:wlan";
		};

		led@37 {
			gpios = <&gpio 37 GPIO_ACTIVE_HIGH>;
			label = "green:wlan_pull_up";
			default-state = "on";
		};

		led@38 {
			gpios = <&gpio 38 GPIO_ACTIVE_LOW>;
			label = "amber:wan";
		};

		led@39 {
			gpios = <&gpio 39 GPIO_ACTIVE_LOW>;
			label = "green:wan";
		};
	};
};
```
The GPIO ids were confirmed in a BCM63xx target and were known to work.

In my BMIPS image, command `ls /sys/class/gpio` gives: `export       gpiochip460  unexport` and `cat /sys/class/gpio/gpiochip460/ngpio` gives `52`. But I remembered in the BCM63xx target, there were two gpiochip instances.

[This wiki page](https://openwrt.org/docs/techref/hardware/soc/soc.broadcom.bcm63xx#gpios) said that:
```
When having more than 32 GPIOs they are splitted between 2 gpiochips. The labels in the Linux kernel are:

bcm63xx-gpio.0
bcm63xx-gpio.1
```
Does the BMIPS target properly handle this?

I also tried removing those leds from dts and control them in software using this method:
https://openwrt.org/docs/techref/hardware/port.gpio#software, it dont work either. I tried setting the GPIOs to low and high, the LED never turned on.

More hardware info can be found here:
https://github.com/rikka0w0/fast3864op-hacks/?tab=readme-ov-file#leds-and-buttons

### OpenWrt version

r25136+1-6497cdba09

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

bmips/bcm63268

### Device

Sagemcom F@st3864OP

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ynezz** [comment]
This is not a bug, because this device is not supported yet. If you want any help during development, you've following options https://openwrt.org/contact

I would try to use [IRC](https://openwrt.org/contact#irc_channels) #openwrt-devel channel first, then if no luck try to send a question email to [openwrt-devel mailing list](https://openwrt.org/contact#mailing_lists) and/or asked on the [forum](https://openwrt.org/contact#forum) in the section for developers.

BTW its quite normal to create a pull request on GitHub during the development and mark it as Draft. There just mention the missing/TODO bits and your current blockers, its very likely, that you might get some help there already as well.
