### ISSUE TITLE
apk: missing dependency on a `wget` provider

### ISSUE THREAD

**Issue by raenye** [openwrt/openwrt#17173]
### Describe the bug

`apk` needs a `wget` provider, (e.g., `uclient-fetch` or `wget-ssl`) to download indices and packages, but does not depend on it, so one might remove `uclient-fetch` (which is installed by default) and get stuck with a malfunctioning build.
This is relevant for both `apk-mbedtls` and `apk-openssl`.

Note that `opkg` depends on `uclient-fetch` (for historical reasons).

@efahl @hnyman 

### OpenWrt version

r0+28167-28f79ae8ba

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/mt7622

### Device

Xiaomi Redmi Router AX6S

### Image kind

Self-built image

### Additional info

See [discussion](https://forum.openwrt.org/t/the-future-is-now-opkg-vs-apk/201164/238) on the forums.
```
root@OpenWrt:~# apk info apk-mbedtls -R
apk-mbedtls-3.0.0_pre20241113-r1 depends on:
libc
libmbedtls21
zlib
```
```
root@OpenWrt:~# apk info apk-openssl -R
apk-openssl-3.0.0_pre20241113-r1 depends on:
libc
libopenssl3
zlib
```
```
root@OpenWrt:~# apk info uclient-fetch -P
uclient-fetch-2024.10.22~88ae8f20-r1 provides:
wget
```
```
root@OpenWrt:~# apk info wget-ssl -P
wget-ssl-1.24.5-r1 provides:
gnu-wget
wget
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by hnyman** [comment]
Related forum discussion starting at
https://forum.openwrt.org/t/the-future-is-now-opkg-vs-apk/201164/238

Like I said in forum, the devs are probably thinking that uclient-fetch is part of premanently installed apps since 158f5b8d7aed in year 2016, and it is not expected that users remove essential packages when they do personal builds.

The list of packages assumed "to be there by default" :
https://github.com/openwrt/openwrt/blob/main/include/target.mk#L21-L35
