### ISSUE TITLE
Asus RT-N16: wifi disappears after touching any parameter

### ISSUE THREAD

**Issue by lemonacid** [openwrt/openwrt#197]
I have Asus RT-N16 hw ver A1.
As recommended at the wiki page for that router replaced kmod-b43 wifi drivers with kmod-brcmsmac.
But i can't change any parameter - after save&apply wifi leaves air and there is only one way to set it to working state back - telnet or ssh into router, remove /etc/config/wireless, reboot and enable wifi interface in luci.
wifi works only in open mode with 'OpenWrt' SSID. If i change everything - SSID, encryption, SSID broadcasting - wifi switches off up to the next config file removal.
i tried both chaos calmer and barrier breaker.

**Comment by brendonofficial** [comment]
@lemonacid I had this issue when using those WiFi drivers, in my case it turned out that hitting 'Save & Apply' was causing the password to be written incorrectly to the configuration file. Perhaps check that `option key '<password>'` in /etc/config/wireless has the correct password, and formatting.
