### ISSUE TITLE
Wireless support for Asus RT-AC87U

### ISSUE THREAD

**Issue by geirgp** [openwrt/openwrt#428]
Wireless it not supported according to https://wiki.openwrt.org/toh/asus/rt-ac87u , reasons specified:

> * BRCM4360 Wireless not supported on Linux → no support in OpenWrt (see bootlog) (2015-08)
> * No Quantenna support in Linux (2015-08)

However, DD-WRT has done it and I have set it up successfully on my RT-AC87U _with_ wireless - both 2.4 and 5Ghz.

What does it take to get this supported in OpenWRT. How can I contribute?

**Comment by razum2um** [comment]
@geirgp I think this is [the answer](http://www.dd-wrt.com/phpBB2/viewtopic.php?p=1004372#1004372) I fear, we have a rare proprietary separate 5gz wifi [Quantenna QSR1000 chip](https://wikidevi.com/wiki/Quantenna), which is used by 13 devices for far. 

Developer in the linked thread points, that there can be a basic support, but as far as I understand they don't want to invest time into this.

I also have subject, on merlin, 5gz sometimes (rarely) gets lost, otherwise, it'k ok. So I'll stick with it
