### ISSUE TITLE
tcpdump over ssh not working

### ISSUE THREAD

**Issue by treaki** [openwrt/openwrt#501]
i am using openwrt on x86 based on openwrt-15.05.1-x86-kvm_guest-combined-ext4 ( CHAOS CALMER (15.05.1, r48532) )

```
ssh root@192.168.57.1 tcpdump -w - > tcpdump02
```
where 192.168.57.1 is my openwrt device and my goal is to capture packages from eth0 to a local file.

But the file stays empty but its sure that there are packages on the interface. When i run the same command on the shell of the device like

```
treaki@ttpdeb:/media/treaki/Elements/vms/os2 warp 4$ ssh root@192.168.57.1


BusyBox v1.23.2 (2016-01-02 14:31:17 CET) built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 CHAOS CALMER (15.05.1, r48532)
 -----------------------------------------------------
  * 1 1/2 oz Gin            Shake with a glassful
  * 1/4 oz Triple Sec       of broken ice and pour
  * 3/4 oz Lime Juice       unstrained into a goblet.
  * 1 1/2 oz Orange Juice
  * 1 tsp. Grenadine Syrup
 -----------------------------------------------------
root@OpenWrt:~# tcpdump -w - | hexdump
tcpdump: WARNING: eth0: no IPv4 address assigned
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
^C32 packets captured
35 packets received by filter
0 packets dropped by kernel

root@OpenWrt:~# tcpdump -w - 
tcpdump: WARNING: eth0: no IPv4 address assigned
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
�ò����1RYGtvv
''�Eh%@@0
            ��9��9�؇Pwr�h��

```

i get output as you see. So i guess that there is a porblem. I have done a workaround using ssh -R and netcat/ncat on both sites which leeds me to my new issue following this.

**Comment by poddmo** [comment]
I was trying to do this the other day. I found that packets did arrive eventually. I put it down to some kind of buffering. Based on the manpage, http://www.tcpdump.org/manpages/tcpdump.1.html, something like immediate mode which has buffering and terminal considerations. Or other buffer options: `-l` and `-U`. The `-w` option also refers to buffering. 

I now tend to think there is something related to the terminal as a simple command run via ssh does not work but works fine on the openwrt system:

Works: 
`root@openwrt:~# tcpdump -ni wlan1 port 53`

Doesn't work:
`user@debian:~$ ssh root@openwrt tcpdump -ni wlan1 port 53`

I left it there because a lot of software in openwrt is stripped down so not all options are available and some packages are older and don't support required feature. I hope this gives you ideas.
