### ISSUE TITLE
Firewall: Default Allow-DHCPv6 rule option src_ip 'fc00::/6' prevents receiving ipv6 DHCP from ISP

### ISSUE THREAD

**Issue by illumiN8i** [openwrt/openwrt#5066]
~~Due to ISP stupidity~~ The default firewall rule for Allow-DHCPv6 prevents receiving an ipv6 address from some ISPs ~~that do this incorrectly~~. In my case, Comcast/Xfinity.

Technical explanation here: https://forum.openwrt.org/t/ipv6-not-working-in-19-07-in-standard-configuration-only-disable-firewall-rules-helped/71883/20

Removing option src_ip 'fc00::/6' works as a workaround but maybe there is a better fix for dealing with ISPs that do this.

**Comment by tiagogaspar8** [comment]
From what I read in RFCs the source can be removed as the RFC states that the source might be the link-local address or a gua address, because it might come from a relay, I don't know if anyone wants to share their thoughts.

**Comment by illumiN8i** [comment]
Do you have a link to the RFC? Allowing this form of DHCPv6 would likely help with ipv6 adoption as there may be openwrt users that are not aware that ipv6 is not working even though it is offered by the ISP.

**Comment by tiagogaspar8** [comment]
So, I can make a pull request for this, but I'd like opinions from people first

**Comment by shelterx** [comment]
Well, if it breaks things I don't see why it shouldn't be fixed?
How do firewalls configure this generally?

**Comment by tiagogaspar8** [comment]
From what I see on google the recommendation is to do the filtering by the port only, maybe that's why others don't face the same issue...
I'll make a pull request then, hope it gets merged, from my experience this doesn't get reviewed, I have a pull request opened for 2 years now, let's hope this one's different

**Comment by tiagogaspar8** [comment]
Hi @illumiN8i or @shelterx can one of you guys send me a pcapng of the dhcpv6 messages you have on the wan (when it's working)? I need to clear out some stuff before making the pull request.

**Comment by tiagogaspar8** [comment]
So, I've been reading and not only should the source line be removed, but both source and destination as there are cases where DHCP can use GUA addresses says the RFC.

I also discovered that the defaults are coded in the firewall4 repo directly for some reason and so the patch should be mailed, which I had never done, so @jow- , since you're the maintainer can you make these quick changes?
I can try but I feel like I would probably do something wrong and be ignored.

**Comment by jow-** [comment]
> so @jow- , since you're the maintainer can you make these quick changes?

Please provide a diff illustrating the changes.

**Comment by tiagogaspar8** [comment]
Hi Jow,
Here you have it:
[0001-config-remove-restictions-on-DHCPv6-allow-rule.patch.txt](https://github.com/openwrt/openwrt/files/8619188/0001-config-remove-restictions-on-DHCPv6-allow-rule.patch.txt)

**Comment by jow-** [comment]
Merged into firewall4.git with https://git.openwrt.org/72b196da and into firewall3 with 65258f5d6093809c541050256646795bc0a460a9

**Comment by tiagogaspar8** [comment]
Thanks Joe! You're the best!😁

**Comment by jow-** [comment]
Fixed with 2df17604a4f891447beb66988e3d83e23ab3a3b0
