### ISSUE TITLE
FS#1670 - consistent naming convention for the imagebuilder.tar.xz URL

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6618]
*attila-lendvai:*

====== context ======

i have a [[https://github.com/attila-lendvai/openwrt-auto-extroot|project/script]] that downloads imagebuilder and builds a custom OpenWRT firmware for any router. the resulting firmware automatically sets up extroot on any external storage.

====== issue ======

the URL for the image builder archive is not easily derivable. see this snippet from my script:

<code>
IMGBUILDER_NAME="lede-imagebuilder-${RELEASE}-${TARGET_ARCHITECTURE}-${TARGET_VARIANT}.Linux-x86_64"

IMGBUILDERURL="https://downloads.openwrt.org/releases/${RELEASE}/targets/${TARGET_ARCHITECTURE}/${TARGET_VARIANT}/${IMGBUILDER_ARCHIVE}"
</code>

it's easy to calculate the URL for e.g. //(ar71xx generic tl-wr1043nd-v2)// because //${TARGET_VARIANT} (i.e. 'generic')// is part of both the dir path and the filename, but not for e.g. //(bcm53xx generic dlink-dir-885l)//, because in the latter case //${TARGET_VARIANT}// is part of the directory structure, but not that of the filename itself.

====== request ======

please make sure that the imagebuilder URL can be consistently calculated from the //(arch, variant, device)// triplet, either by eliminating the variant also from the dir structure, or by consistently including it in the file name, too.

**Comment by attila-lendvai** [comment]
i'm the original reporter of this issue. if i get write access to it, then i can revise it to read better on GH.

**Comment by ynezz** [comment]
This is probably very old report and it's fixed already, since I see following situation for the last 2 releases and current development snapshot:

* https://downloads.openwrt.org/releases/19.07.9/targets/ar71xx/nand/openwrt-imagebuilder-19.07.9-ar71xx-nand.Linux-x86_64.tar.xz
* https://downloads.openwrt.org/releases/21.02.2/targets/bcm53xx/generic/openwrt-imagebuilder-21.02.2-bcm53xx-generic.Linux-x86_64.tar.xz
* https://downloads.openwrt.org/snapshots/targets/ath79/tiny/openwrt-toolchain-ath79-tiny_gcc-11.2.0_musl.Linux-x86_64.tar.xz
