### ISSUE TITLE
FS#3490 - Please include Full Cone NAT package

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8358]
*fullcone:*

The default OpenWrt netfilter implements “Port Restricted Cone” NAT. Sometimes it’s useful to have less restricted NAT.

Someone recently created a netfilter extension that implements “Full Cone” NAT. Please include it in the package feeds.

Full Cone NAT description:
https://tools.ietf.org/html/rfc3489#section-5

Netfilter extension:
https://github.com/Chion82/netfilter-full-cone-nat

OpenWrt package:

https://github.com/LGA1150/openwrt-fullconenat
https://github.com/LGA1150/fullconenat-fw3-patch

**Comment by 981213** [comment]
As no one wants to maintain an OOT module in the main OpenWrt tree, there are two possible solution to this:
1. the kernel module itself should be upstreamed and we can backport it afterwards.
2. Someone submit the package into the community package feed: https://github.com/openwrt/packages

**Comment by Lanchon** [comment]
a bit more info here... https://github.com/openwrt/openwrt/issues/9248#issuecomment-1207461963

**Comment by fanthos** [comment]
Some new codes:
https://github.com/fullcone-nat-nftables/

**Comment by 981213** [comment]
Let me emphasise this again:
We have no interest in **maintaining** such an out-of-tree kernel module, meaning:
1. We don't want to be responsible for fixing any bugs that may be caused by these random OOT kernel modules.
2. We don't want to put in extra efforts in forward-porting these modules to newer kernel versions in the future.

Also, we are less adequate at properly reviewing these modules comparing to the netfilter maintainers at linux upstream.

OpenWrt firewall relies on infrastructures provided by the Linux Netfilter project. If it's implemented in mainline Linux, OpenWrt will automatically get this function supported.

I hope I've explained clearly that here is not the right place for this discussion, and OpenWrt maintainers are not the proper people to review these kernel modules. (See also: https://github.com/openwrt/openwrt/issues/9248#issuecomment-1251425303) Please redirect your discussion and/or code to the upstrem Linux Netfilter project instead.

I'm closing this issue as won't fix.

**Comment by marekm72** [comment]
Understood.  Could you point me in the right direction, as the upstream Linux Netfilter project seems to be mature, not very actively maintained, but perhaps I'm looking in the wrong places?

**Comment by 981213** [comment]
For patch submission you could follow the Linux kernel contribution guide here: https://www.kernel.org/doc/html/latest/process/submitting-patches.html
For other general discussion with the netfilter community you may send emails to a suitable netfilter mailing list described at: https://www.netfilter.org/mailinglists.html
As with other open-source projects, you can expect a proper review of the patches if you submit the code, but it's unlikely that someone will implement these for you when you are just talking.
