### ISSUE TITLE
FS#3646 - Unable to Swap /proc/swaps does not exist (ramips rt305x/)

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#8682]
*xapukserge:*

1) 
Device Dlink DIR320 rev.B1
OpenWrt 19.07.7 r11306-c4a6851c72 / LuCI openwrt-19.07 branch git-21.044.30835-34e0d65

2)
Istalled packages: 
  block-mount
  kmod-usb-core
  kmod-usb2
  kmod-usb-ohci
  kmod-usb-storage
  kmod-fs-ext4
  zram-swap
  swap-utils 

3)
How-to:
root@OpenWrt:~# mkswap /dev/sda1
mkswap: /dev/sda1: warning: wiping old swap signature.
Setting up swapspace version 1, size = 511 MiB (535818240 bytes)
no label, UUID=5413e04d-954e-493c-b26d-926a67af1bbc

root@OpenWrt:~# swapon -a
 block: failed to swapon /dev/sda1

root@OpenWrt:~# cat /proc/swaps
  cat: can't open '/proc/swaps': No such file or directory

So, I think, swap module was accidentally turned off during building firmware, because OpenWRT build version 18.06 works fine!

**Comment by 981213** [comment]
Swap support is disabled for small_flash targets to save space. This isn't really a bug.

**Comment by KOLANICH** [comment]
I wonder if swap support can be provided as separate packages. Because now I have 3 MiB of free space on flash (Keenetic and Keenetic Lite b, 8 MiB flash size), but I'm short on RAM (32 MiB).

Also I'm thinking about replacing flash and RAM chips, but rebuilding the kernel takes long and is a memory-hungry process, so it may be cheaper to throw the routers into garbage and buy new ones, instead of building an own kernel for every release.

**Comment by 981213** [comment]
Unfortunately mtd devices can't be used as swap. You need block devices such as a USB flash drive for swap to work.

> so it may be cheaper to throw the routers into garbage and buy new ones, instead of building an own kernel for every release.

Agree :)
